[project]
name = 'PetChain-Care-Network'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.adoption-verification-system]
path = 'contracts/adoption-verification-system.clar'
clarity_version = 3
epoch = '3.2'

[contracts.pet-identity-registry]
path = 'contracts/pet-identity-registry.clar'
clarity_version = 3
epoch = '3.2'

[contracts.responsible-pet-rewards]
path = 'contracts/responsible-pet-rewards.clar'
clarity_version = 3
epoch = 'latest'

[contracts.veterinary-care-tracking]
path = 'contracts/veterinary-care-tracking.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
